### ISSUE TITLE
File path on all comments in one message is absolute

### ISSUE THREAD

**Issue by dcsobral** [jenkinsci/violation-comments-to-stash-plugin#15]
This is the comment on a file:

```
Reporter: FINDBUGS
Rule: DMI_RANDOM_USED_ONLY_ONCE
Severity: WARN
File: com/rr/util/CheckStyleFindbugsCoverage.java L29
Source: com.rr.util.CheckStyleFindbugsCoverage
```

And this is the comment with all:

```
Reporter: CHECKSTYLE
Rule: com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocParagraphCheck
Severity: WARN
File: /mnt/mesos/sandbox/jenkins/workspace/root_pipeline/common/util/src/main/java/com/rr/util/CheckStyleFindbugsCoverage.java L14
```

Maybe the difference is that one was generated by checkstyle and the other by findbugs? Either way, I'd really like to get rid of the absolute path if it's relative to the workspace. Given `Path`s `file` and the workspace directory at `base`, this does the trick: `base.relativize(file)`, if it happens that it is checkstyle producing absolute paths, and not the style of comment.

**Comment by tomasbjerre** [comment]
Should be fixed in 1.46 now. Using the file paths reported by Bitbucket Server.
