### ISSUE TITLE
Could you extend documentation how to comment at https://bitbucket.org

### ISSUE THREAD

**Issue by Arbuzov** [jenkinsci/violation-comments-to-stash-plugin#16]
Try to use many ways but got nothing.

    step([

            $class: 'ViolationsToBitbucketServerRecorder', 

                config: [

                    bitbucketServerUrl: 'https://api.bitbucket.org/', 

                    createCommentWithAllSingleFileComments: true, 

                    createSingleFileComments: true, 

                    projectKey: 'EVANTI', 

                    repoSlug: 'cabinet-radugainternet-ru', 

                    pullRequestId: "${pr}", 

                    useUsernamePassword: true, 

                    username: 'admin', 

                    password: 'admin', 

                    useUsernamePasswordCredentials: false, 

                    violationConfigs: [

                        [ pattern: 'check_style.xml', reporter: 'CHECKSTYLE' ]

                    ]

                ]

            ])

see at log

    Error calling:

    https://api.bitbucket.org/rest/api/1.0/projects/EVANTI/repos/cabinet-radugainternet-ru/pull-requests/683/changes?limit=999999
    GET
     null

`

**Comment by tomasbjerre** [comment]
The plugin is for Bitbucket Server (or Stash). Bitbucket.org has completely different API:s and is not supported.

**Comment by tomasbjerre** [comment]
https://confluence.atlassian.com/bitbucketserver/bitbucket-rebrand-faq-779298912.html#BitbucketrebrandFAQ-Whyaren'ttheServerandCloudfeaturesthesame?
