### ISSUE TITLE
Plugin aborts if it fails to delete a message

### ISSUE THREAD

**Issue by dcsobral** [jenkinsci/violation-comments-to-stash-plugin#17]
It seems the plugin aborts if it fails to delete a comment it created on a previous build. Unfortunately, comments that have been used as anchor for tasks are not deletable, so I get this:
```
[StaticAnalysisCheck] Error calling:
[StaticAnalysisCheck] https://git.richrelevance.com/rest/api/1.0/projects/RR/repos/root/pull-requests/257/comments/95485?version=0
[StaticAnalysisCheck] DELETE
[StaticAnalysisCheck] null
```
And then the plugin stops without doing anything else.

**Comment by tomasbjerre** [comment]
Should be fixed in 1.25. Available in update sites within a few hours. Open issue again if not fixed.
