### ISSUE TITLE
2.2* Jenkins configuration help

### ISSUE THREAD

**Issue by vitalyiegorov** [jenkinsci/violation-comments-to-stash-plugin#18]
Can you please provide screens for configuration similar to this, i am fighting this for more than a week already and no luck https://www.dropbox.com/s/82xx4eygdy8xi34/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202016-09-21%2020.54.09.png?dl=0
@tandibar

**Comment by tomasbjerre** [comment]
Bitbucket.org is not Bitbucket Server. Its a completely different product. So sorry, its not supported!

**Comment by vitalyiegorov** [comment]
And what is the difference between them? They should be equal @tomasbjerre

**Comment by tomasbjerre** [comment]
You can google that.

Den 21 sep. 2016 21:40 skrev "Vitaly Iegorov" <notifications@github.com>:

**Comment by vitalyiegorov** [comment]
@tomasbjerre You are absolutely right, https://answers.atlassian.com/questions/37851717/is-there-documentation-on-rest-api-differences-bitbucket-server-vs-bitbucket-cloud

How do you think which would be the best option: 
* to create a separate plugin for BitBucket.org based on this repo
* to add BitBucket.org support to this repo

**Comment by tomasbjerre** [comment]
New repo. I also made such a plugin for Github [in its own repo](https://github.com/jenkinsci/violation-comments-to-github-plugin).

They share some functionality through [violation-comments-lib](https://github.com/tomasbjerre/violation-comments-lib).

**Comment by tomasbjerre** [comment]
Cloud support here: https://github.com/tomasbjerre/violation-comments-to-bitbucket-cloud-command-line
