### ISSUE TITLE
Support pylint output

### ISSUE THREAD

**Issue by tuukkamustonen** [jenkinsci/violation-comments-to-stash-plugin#20]
Add support for reading pylint-format.

```
pylint --output-format=parseable --reports=n . > pylint.out
```

I tried configuring `pylint.out` file as FLAKE8 source file, but it produces something like:

```
************* Module fs.libcheck.libcheck
/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/fs/libcheck/libcheck.py:322: [C0330(bad-continuation), ] Wrong hanging indentation before block (add 4 spaces).
                    name == 'used_in_products' and self.presets.get('product') and
                    ^   |
```

Plugin output:

```
Dangling meta character '*' near index 0
*/pylint\.out
^
```

Pylint is also used by [prospector](https://github.com/landscapeio/prospector). It allows reporting violations from various tools in pylint-format, so supporting pylint would tackle a bunch of tools. Prospector also supports other output formats (json, yaml, etc.), but I think those formats are less de-facto and supporting pylint would be the best bet.

**Comment by tuukkamustonen** [comment]
Uh, too many expectations and I should actually read the error message before opening a ticket. Apparently this was caused by an invalid regex to file pattern...

**Comment by tuukkamustonen** [comment]
@tomasbjerre Although, it's a bit confusing that front page says:

![image](https://cloud.githubusercontent.com/assets/94327/19644977/28f78a5a-99fb-11e6-9ef2-325adf148cec.png)

while Flake8- and Pylint-formats are different and `flake8` does not execute pylint internally.

If the tool really already supports pylint-output, I would suggest to change README as:

```
- Flake8 (Pep8, Mccabe, PyFlakes) / PyLint
```

And on configuration page, put:

```
FLAKE8 / PYLINT:    _______________________
```

...just to make it more evident?

**Comment by tomasbjerre** [comment]
I can add a pylint parser if you have a sample pylint report? Command for generating it and its output.

**Comment by tuukkamustonen** [comment]
Alright, I added couple of gists (with pylint 1.6.4):

https://gist.github.com/tuukkamustonen/a9994bb4eededde6c3095eba922e73c3
https://gist.github.com/tuukkamustonen/78d38559176eea7cfb87d74072b4c86e

**Comment by tomasbjerre** [comment]
I just released this. Should be in the Jenkins update center within a few hours.

**Comment by tuukkamustonen** [comment]
Thanks, I'll give it a spin tomorrow!

**Comment by tuukkamustonen** [comment]
It seems to work, but it be possible to include also the "numeric" rule ID into `Rule` field:

```
Found 1 violation:
Reporter: PYLINT
Rule: anomalous-backslash-in-string
Severity: WARN
File: fs/csm/admin_api/admin_api.py L1086

Anomalous backslash in string: '\s'. String constant might be missing an r prefix.
<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>
```

Normally you discuss/ignore/google per rule ID (e.g. `E1101`) rather than it's label. Perfect output would be something like:

```
Rule: W1401(anomalous-backslash-in-string)
```

**Comment by tomasbjerre** [comment]
Should be fixed in 1.31!

**Comment by tomasbjerre** [comment]
I just realized I missed the severity level... I'll fix that later.

**Comment by tomasbjerre** [comment]
Open issue again if not fixed!
