### ISSUE TITLE
Pretty print violations comments

### ISSUE THREAD

**Issue by tuukkamustonen** [jenkinsci/violation-comments-to-stash-plugin#25]
Violations comments could use some formatting. It's quite ugly now:

![image](https://cloud.githubusercontent.com/assets/94327/19760039/54a9a554-9c38-11e6-998e-57e342d8e510.png)

Maybe:

![image](https://cloud.githubusercontent.com/assets/94327/19760264/8f2f3f12-9c39-11e6-9fcc-bf6352f86d79.png)

Or even:

![image](https://cloud.githubusercontent.com/assets/94327/19760277/a1ab38d0-9c39-11e6-8b17-b51a87f24925.png)

(Table-formatting actually eats up some more space so not sure... but it looks nice).

Implement these with the following markdown:

```
**Reporter**: PYLINT
**Rule**: `0326`(bad-whitespace)
**Severity**: INFO
**File**: fs/csm/common/util.py L40

No space allowed around keyword argument assignment
*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>*

| | |
|---|---|
| **Reporter** | PYLINT |
| **Rule** | `0326`(bad-whitespace) |
| **Severity** | INFO |
| **File** | fs/csm/common/util.py L40 |
| **Message** | No space allowed around keyword argument assignment |

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>*
```

**Comment by tomasbjerre** [comment]
I did pick the first one. Should be fixed in 1.33. Open issue again if any problems!
