### ISSUE TITLE
Violations Comment too long for Bitbucket Server

### ISSUE THREAD

**Issue by mike10010100** [jenkinsci/violation-comments-to-stash-plugin#26]
When the plugin posts a comment resulting from a particularly bad linting session (with tons of violations), the following error occurs:

```
{
  "errors": [
    {
      "context": "text",
      "message": "Please enter a non-empty value less than 32768 characters",
      "exceptionName": null
    }
  ]
}
```

Would it be possible to break up the posting of the comments into properly-sized chunks?

**Comment by tomasbjerre** [comment]
Should be fixed in 1.33. Open issue again if any problems!
