### ISSUE TITLE
Changelog missing from last few releases

### ISSUE THREAD

**Issue by tuukkamustonen** [jenkinsci/violation-comments-to-stash-plugin#30]
1.36 and 1.37 are missing in `CHANGELOG.md`.

**Comment by tuukkamustonen** [comment]
Actually, looks like 1.37 changes are written there under `Unreleased`, which should be placeholder for 1.36?

**Comment by tomasbjerre** [comment]
Its generated [from Git with a plugin](https://github.com/jenkinsci/violation-comments-to-stash-plugin/blob/master/pom.xml#L122). Forgot to run the plugin. Fixed now!
