### ISSUE TITLE
Adding release notes to Jenkins plugin page

### ISSUE THREAD

**Issue by Szasza** [jenkinsci/violation-comments-to-stash-plugin#32]
First of all congrats on the plugin, great work.

Would it be possible to add a _Release notes_ section to the bottom of the plugin page https://wiki.jenkins-ci.org/display/JENKINS/Violation+Comments+to+Bitbucket+Server+Plugin ? Most of the Jenkins plugins have that so one can easily check what the changes and potential risks are before an upgrade.

Thank you in advance for the consideration.

**Comment by tomasbjerre** [comment]
There is a changelog here:
https://github.com/jenkinsci/violation-comments-to-stash-plugin/blob/master/CHANGELOG.md

Its autogenerated with:
https://github.com/tomasbjerre/git-changelog-maven-plugin

I will add a link to it from the wiki!
