### ISSUE TITLE
No PR comments for Finbugs

### ISSUE THREAD

**Issue by goostleek** [jenkinsci/violation-comments-to-stash-plugin#33]
I have configured the plugin for _Checkstyle_ and _Findbugs_ violations but only _Checkstyle_ comments are visible in the PR. Do you have any suggestions how I can investigate the reason of having no comments for _Findbugs_? Last part of my Jenkins PR builder job log is:

```
---
--- Jenkins Violation Comments to Bitbucket Server ---
---
bitbucketServerUrl: [REDACTED]
projectKey: BEST
repoSlug: [REDACTED]
pullRequestId: 201
usernamePasswordCredentialsId: true
username: false
password: false
createSingleFileComments: true
createCommentWithAllSingleFileComments: false
commentOnlyChangedContent: false
commentOnlyChangedContentContext: 0
ANDROIDLINT with pattern 
CHECKSTYLE with pattern .*/checkstyle-result\.xml$
CODENARC with pattern 
CPD with pattern 
CPPCHECK with pattern 
CPPLINT with pattern 
CSSLINT with pattern 
FINDBUGS with pattern .*/findbugsXml\.xml$
FLAKE8 with pattern 
FXCOP with pattern 
GENDARME with pattern 
JCREPORT with pattern 
JSHINT with pattern 
LINT with pattern 
MYPY with pattern 
PERLCRITIC with pattern 
PITEST with pattern 
PMD with pattern 
PYDOCSTYLE with pattern 
PYLINT with pattern 
RESHARPER with pattern 
SIMIAN with pattern 
STYLECOP with pattern 
XMLLINT with pattern 
ZPTLINT with pattern 
Using username and password from credentials
Will comment 201
Workspace: /var/jenkins_home/jobs/[REDACTED]-pull-request-builder/workspace
Found 3 violations from ViolationConfig [reporter=CHECKSTYLE, pattern=.*/checkstyle-result\.xml$].
Found 25 violations from ViolationConfig [reporter=FINDBUGS, pattern=.*/findbugsXml\.xml$].
Will comment PR BEST/[REDACTED]/201 on [REDACTED]
Notified Stash for commit with id c0d13ffe5273c2a3bdd5e7e06258f0f1466b0a1c
Finished: SUCCESS
```
I'm using the latest version of the plugin (`1.43`)

**Comment by tomasbjerre** [comment]
If you look at the server-log of Jenkins instance. Perhaps there is a stacktrace?

**Comment by tomasbjerre** [comment]
And are you sure that the findbugsXml.xml contains findings on files that were changed in the PR?

**Comment by goostleek** [comment]
Yes, I can browse all violations on the particular Jenkins build. Additionally the log output I added above contains the line telling there are `25` violations
```
Found 25 violations from ViolationConfig [reporter=FINDBUGS, pattern=.*/findbugsXml\.xml$].
```

Unfortunately I don't have access to Jenkins master log files yet to dig deeper into it. Once I have I'll try to update the issue to provide more info about the issue.

**Comment by tomasbjerre** [comment]
If you can attach the findbugs.xml-file here that might help.

**Comment by goostleek** [comment]
I'm affraid this is not an option. at the moment. The client I work for is very concerned about privacy of the source code. But when I have time I will prepare some dummy project to provide some example Findbugs output.

**Comment by goostleek** [comment]
Ok, I have solved the issue. The problem was that I have misused the plugin. Although the build has several Findbugs warnings the PRs used in testing the configuration do not contain the affected code. Once I have added some code with a new Findbugs warning to the PR they appear immediately as a PR comment.

It works as expected now. However I still don't have the comments placed in the right place. I would expect to have the comment placed in the file at the a line which is reported by Findbugs. At the moment the comment is presented only in the _Overview_ tab of the particular PR (in the _Activity_ section). 

(If you need I can include a screenshot to show how it looks)

**Comment by tomasbjerre** [comment]
Did you perform the merge before performing the analysis?

Den 27 feb. 2017 12:11 PM skrev "Marcin Kłopotek" <notifications@github.com

**Comment by goostleek** [comment]
No, I'm using PR builder approach. The Findbug analysis is done on the branch used to create the PR. Are you suggesting to merge it back to parent branch to fix this?

**Comment by tomasbjerre** [comment]
Yes. Let Jenkins merge source branch into target branch and perform the analysis. Without pushing the merge-commit ofcourse =)
