### ISSUE TITLE
Pattern 'filename\\.xml' at the root of the workspace is not found

### ISSUE THREAD

**Issue by sirde** [jenkinsci/violation-comments-to-stash-plugin#35]
When generating the cppcheck.xml file at the root of the workspace and setting the pattern to 'cppcheck\\.xml' the plugin did not find the file. I had to set the pattern to '.*/*cppcheck\\.xml$' to find it which took me some time. 

Is it possible to change it or document it ?

Also for diagnostic it would help to log the name (or number) of file found as the log "Found 0 violations from ViolationConfig [reporter=CPPCHECK..." doesn't indicate if there was an empty file or if no file was found.

Thanks for the great plugin !

**Comment by tomasbjerre** [comment]
Did you notice this text?
https://github.com/jenkinsci/violation-comments-to-stash-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/jvctb/ViolationsToBitbucketServerRecorder/config.jelly#L97

It can be changed a bit to communicate that the pattern is matched against the absolute path:
https://github.com/tomasbjerre/violations-lib/blob/master/src/main/java/se/bjurr/violations/lib/reports/ReportsFinder.java#L29

Which explains why only the second one here is matching:
* https://jex.im/regulex/#!embed=false&flags=&re=cppcheck%5C.xml
* https://jex.im/regulex/#!embed=false&flags=&re=.*%2F*cppcheck%5C.xml%24

If you set the Jenkins server to log *fine*, you should be able to see these logs:
https://github.com/tomasbjerre/violations-lib/blob/master/src/main/java/se/bjurr/violations/lib/ViolationsReporterApi.java#L42
Stating how many files were found. Perhaps that should be made more visible.

**Comment by sirde** [comment]
Thanks for the feedback.
Yes I did notice this text, but assumed that the initial ".*/" was for the "anywhere" condition and was not needed for a file located at root.

Good to know for the "fine" logs.

Anyway that's working nice for me now that it's configured correctly, adding those info in the doc could help some others ;)
