### ISSUE TITLE
Individual comments and keeping previous comments

### ISSUE THREAD

**Issue by leinardi** [jenkinsci/violation-comments-to-stash-plugin#37]
Hi, I was wondering if there is a way to always have individual comments, even if there are multiple comments on the same file or even row.

I tried to set `createCommentWithAllSingleFileComments` and `createSingleFileComments` both to false but than I got no comments at all.

Also I would like to know if is possible to keep the previous comments when I trigger a build a second time. I'm asking because my current pipeline build multiple flavors of the same Android App using multiple parallel jobs and every single job calls the `ViolationsToBitbucketServerRecorder` but it seems that every time is called, for the same PR, it removes the previous report comments.

**Comment by tomasbjerre** [comment]
The createCommentWithAllSingleFileComments should create one comment per violation.

There is currently no option to not delete old comments.

**Comment by leinardi** [comment]
Hey, thanks for the answer. 
I already tried to set `createCommentWithAllSingleFileComments` to true but I got a single comment with all the violations on it. What value should I set to `createSingleFileComments`? I had both set to true iirc.

Any plan to add the option to keep the previous comments?

**Comment by tomasbjerre** [comment]
Here is where it happens:
https://github.com/tomasbjerre/violation-comments-lib/blob/master/src/main/java/se/bjurr/violations/comments/lib/CommentsCreator.java#L59

Sorry, it is the other one. Set `createSingleFileComments` to `true` to create individual comments.

**Comment by leinardi** [comment]
I already have it set to true and most of the time it works fine but for some violation it still create a file comment instead of a line comment:

![image](https://user-images.githubusercontent.com/273338/29865875-fe3ed8e8-8d76-11e7-9f6d-f7d89dacfadb.png)

The second comment should have been created on line 26 but instead was created as file comment.

```
step([
                    $class: 'ViolationsToBitbucketServerRecorder',
                    config: [
                            bitbucketServerUrl                    : 'https://xxxxx.com',
                            createCommentWithAllSingleFileComments: false,
                            createSingleFileComments              : true,
                            commentOnlyChangedContent             : false,
                            projectKey                            : "${PULL_REQUEST_TO_REPO_PROJECT_KEY}",
                            repoSlug                              : "${PULL_REQUEST_TO_REPO_SLUG}",
                            pullRequestId                         : "${PULL_REQUEST_ID}",
                            useUsernamePassword                   : false,
                            username                              : '',
                            password                              : '',
                            useUsernamePasswordCredentials        : true,
                            usernamePasswordCredentialsId         : 'mobile_ci',
                            minSeverity                           : 'INFO',
                            violationConfigs                      : [
                                    [pattern: ".*/reports/lint-results-.*\\.xml\$", parser: 'ANDROIDLINT', reporter: "Lint ${flavor}"],
                                    [pattern: ".*/checkstyle/.*\\.xml\$", parser: 'CHECKSTYLE', reporter: "Checkstyle ${flavor}"],
//                                    [pattern: '.*/findbugsXml\\.xml$', parser: 'FINDBUGS', reporter: 'Findbugs'],
//                                    [pattern: '.*/pmd\\.xml$', parser: 'PMD', reporter: 'PMD'],
                            ]
                    ]
            ])
```

**Comment by tomasbjerre** [comment]
What you refer to as "a file comment" is the same thing as the first comment.

It is just that the first comment were on a part of the file that was changed in the PR and the second was not.

You can set `commentOnlyChangedContent` to `true` in order to only comment changed content. And also the `commentOnlyChangedContentContext` to, perhaps, `2` in order to comment on violations that are reported in the near context of changed lines.

**Comment by leinardi** [comment]
Oh ok, this sound interesting. Can I ask you what is the value of the `commentOnlyChangedContentContext`? Are those the number of lines above and below the violation (eg: line 29 +- 2 lines)? Is there a maximum value?

**Comment by tomasbjerre** [comment]
yes. No maximum value.

**Comment by leinardi** [comment]
It doesn't seem to work, as you can see I changed something just 3 lines before the "legacy" violation but still it didn't create an in line comment, like it did for the new code:
![image](https://user-images.githubusercontent.com/273338/29871315-9f622fd6-8d8b-11e7-8109-077268c11062.png)

```
                                createCommentWithAllSingleFileComments: false,
                                createSingleFileComments              : true,
                                commentOnlyChangedContent             : true,
                                commentOnlyChangedContentContext      : 100,
```

**Comment by tomasbjerre** [comment]
Looks good to me.

You introduced a violation on line 33. You have a context of 100 and line 29 is indeed withing that context.

You might be confused about how Bitbucket displays the violation on line 29, but that has nothing to do with the plugin. It is simply up to Bitbucket to display it like that.

**Comment by leinardi** [comment]
Ok I see, thanks for the answers :)

**Comment by Onlinedispatcher** [comment]
Thank you :)
Can I vote for an option to not delete old comments :)?
The reason for this is, that developers always gets mails for the same issues :) (for every new commit in a PR)

**Comment by tomasbjerre** [comment]
Sounds like you are asking for 2 new features
* Not deleting old comments
* Not commenting on the same violation again if old comment exists

**Comment by Onlinedispatcher** [comment]
Hey :),

jupp you are completely right. 
* Not deleting old comments (because of multiple flavors build in parallel)
* Not commenting on the same violation again if old comment exists

**Comment by tomasbjerre** [comment]
Releasing it now. There is a new config parameter `keepOldComments` that you will want to set to `true`.
```
...
keepOldComments: true,
...
```
Open issue again if not working.
