### ISSUE TITLE
Found 0 violations in PMD-formatted file

### ISSUE THREAD

**Issue by churowa** [jenkinsci/violation-comments-to-stash-plugin#39]
I don't know if this is user-error or not, but I'm struggling to understand where I've gone wrong.

Here is a gist with both the PMD-formatted file itself and the commands I'm using to generate it. If there's something I'm missing, I'd love a point in the right direction!

https://gist.github.com/churowa/bd669d394116dd0c3b65cc2c1c7e430a

**Comment by tomasbjerre** [comment]
Did you perform the merge into target before analysis was done?

**Comment by churowa** [comment]
Hi Tomas, thank you for taking the time to ask!

I don't believe I did. I'm honestly not sure, unless it's something that Bitbucket Server/Jenkins is doing in the background. 

What I have is mostly static analysis, but I'm hoping to use the plugin to comment on my pull request.

Essentially, my Jenkinsfile:
- Builds the codebase
- Runs OCLint static analysis, generating a PMD-formatted report (oclint.log)
- Runs the Violation Comments to Bitbucket Server plugin to (hopefully) post the results back to the PR as comments.

I should note that the plugin is *working* with another file I have containing the build log (output.clang). So the CLANG parser is commenting on my PR, but the PMD parser is not.

**Comment by churowa** [comment]
`Found 0 violations from ViolationConfig [pattern=.*/oclint\.log$, reporter=Pmd, parser=PMD]`

I **think** that the oclint.log file is properly formatted PMD-style output. I may be wrong. Looking at the test code in Violations Lib, I think it looks most similar to the PHPMD version, but it's missing a timestamp.

I'm sorry. I know I'm not being terribly helpful, I'm learning as I go.

But I have spent a lot of time debugging how the plugin is used, through the other result file I have that does work (output.clang). I had to generate that file by hand, through trial and error, from some json output from xcpretty.

**Comment by tomasbjerre** [comment]
You must first perform the merge. Something like:
```
 stage('Merge') {
  sh "git init"
  sh "git fetch --no-tags --progress git@git:group/reponame.git +refs/heads/*:refs/remotes/origin/* --depth=200"
  sh "git checkout origin/${env.targetBranch}"
  sh "git merge origin/${env.sourceBranch}"
  sh "git log --graph --abbrev-commit --max-count=10"
 }
```

If the merge is note performed before analysis, then the reported lines will not match the lines in the PR. And no violations will be reported.

**Comment by churowa** [comment]
Ahh, that makes a lot of sense! Maybe that's my problem.

I will try and do this. Honestly, I thought that because I was checking out the PR branch from Bitbucket Server that it *was* merged. My mistake. I'll close this once I get it working.

Thanks Tomas

**Comment by tomasbjerre** [comment]
This might have been solved with https://github.com/tomasbjerre/violations-lib/issues/27
