### ISSUE TITLE
Found 0 violations from ViolationConfig

### ISSUE THREAD

**Issue by jansohn** [jenkinsci/violation-comments-to-stash-plugin#41]
I'm using your plugin in combination with the `Bitbucket Branch Source Plugin` (https://wiki.jenkins.io/display/JENKINS/Bitbucket+Branch+Source+Plugin) which performs the merge of the PR upon checkout:

     > C:\Program Files\Git\cmd\git.exe rev-parse --is-inside-work-tree # timeout=10
    Fetching changes from 2 remote Git repositories
     > C:\Program Files\Git\cmd\git.exe config remote.origin.url ssh://git@xyz.com:1234/TEST/repo.git # timeout=10
    Fetching without tags
    Fetching upstream changes from ssh://git@xyz.com:1234/TEST/repo.git
     > C:\Program Files\Git\cmd\git.exe --version # timeout=10
    using GIT_SSH to set credentials SSH key access on Bitbucket server
     > C:\Program Files\Git\cmd\git.exe fetch --no-tags --progress ssh://git@xyz.com:1234/TEST/repo.git +refs/pull-requests/27/from:refs/remotes/origin/PR-27
     > C:\Program Files\Git\cmd\git.exe config remote.upstream.url ssh://git@xyz.com:1234/TEST/repo.git # timeout=10
    Fetching without tags
    Fetching upstream changes from ssh://git@xyz.com:1234/TEST/repo.git
    using GIT_SSH to set credentials SSH key access on Bitbucket server
     > C:\Program Files\Git\cmd\git.exe fetch --no-tags --progress ssh://git@xyz.com:1234/TEST/repo.git +refs/heads/master:refs/remotes/upstream/master
    Merging remotes/upstream/master commit 2256767148ed57775c05af2b7a85d78a5388831f into PR head commit b600ebce173b62c7b68b6c080c5b07be4c039429
     > C:\Program Files\Git\cmd\git.exe config core.sparsecheckout # timeout=10
     > C:\Program Files\Git\cmd\git.exe checkout -f b600ebce173b62c7b68b6c080c5b07be4c039429
     > C:\Program Files\Git\cmd\git.exe merge 2256767148ed57775c05af2b7a85d78a5388831f # timeout=10
     > C:\Program Files\Git\cmd\git.exe rev-parse "HEAD^{commit}" # timeout=10
    Merge succeeded, producing 864bbaa3e1ebd8d88d82b1a0d425f20949c40dc7
    Checking out Revision 864bbaa3e1ebd8d88d82b1a0d425f20949c40dc7 (PR-27)
     > C:\Program Files\Git\cmd\git.exe config core.sparsecheckout # timeout=10
     > C:\Program Files\Git\cmd\git.exe checkout -f 864bbaa3e1ebd8d88d82b1a0d425f20949c40dc7
    Commit message: "Merge commit '2256767148ed57775c05af2b7a85d78a5388831f' into HEAD"
     > C:\Program Files\Git\cmd\git.exe rev-list 0bd249813f3a6c3e5a16bbe10325ae3877ac68c3 # timeout=10

Afterwards I build the project and it produces the `Checkstyle` and `Findbugs` result files in `target\checkstyle-result.xml` and `target\findbugsXml.xml`. The PR contains a change which produces a new Findbugs warning which is also displayed in the `findbugsXml.xml` file as a `BugInstance`.

The plugin however does not seem to find any violations.

    ---
    --- Jenkins Violation Comments to Bitbucket Server ---
    ---
    bitbucketServerUrl: https://xyz.com
    projectKey: TEST
    repoSlug: repo
    pullRequestId: 28
    usernamePasswordCredentialsId: true
    username: false
    password: false
    createSingleFileComments: true
    createCommentWithAllSingleFileComments: false
    commentOnlyChangedContent: false
    commentOnlyChangedContentContext: 0
    minSeverity: INFO
    keepOldComments: false
    Checkstyle with pattern .*/checkstyle-result\.xml$
    Findbugs with pattern .*/findbugsXml\.xml$
    Using username and password from credentials
    Pull request: 28
    Workspace: D:\app\BuildServer\jenkins-data\jobs\Repo\branches\PR-28\workspace
    Found 0 violations from ViolationConfig [pattern=.*/checkstyle-result\.xml$, reporter=Checkstyle, parser=CHECKSTYLE].
    Found 0 violations from ViolationConfig [pattern=.*/findbugsXml\.xml$, reporter=Findbugs, parser=FINDBUGS].
    PR: TEST/repo/28 on https://xyz.com

Any idea what I'm doing wrong? Jenkins is running on Windows btw...

**Comment by tomasbjerre** [comment]
It could be the `.*/checkstyle-result\.xml$` that should be `.*\\checkstyle-result\.xml$` on Windows.

**Comment by jansohn** [comment]
Tried that before, didn't help unfortunately... Is there a way to debug if the regex matches or not?

**Comment by tomasbjerre** [comment]
You may also try to just skip the initial slash. `.*checkstyle-result\.xml$`.

There is no debug-logging for this. It is done here: https://github.com/tomasbjerre/violations-lib/blob/master/src/main/java/se/bjurr/violations/lib/reports/ReportsFinder.java#L30

**Comment by jansohn** [comment]
Excellent, now it's working!
