### ISSUE TITLE
Password in clear text

### ISSUE THREAD

**Issue by casz** [jenkinsci/violation-comments-to-stash-plugin#44]
The way you use credentials plugin is bad, you should never put the password in clear text, which you do several times through logging and in config xml 🙈 🙉 🙊 
Working on a PR that fixes a lot of your jelly hacking and going to deprecate the use of username and password.

**Comment by casz** [comment]
Takes the credentials and paste it into clear text
https://github.com/jenkinsci/violation-comments-to-stash-plugin/blob/0e85c4f0d557f03f9a5a6b108af9f90bac9de1d5/src/main/java/org/jenkinsci/plugins/jvctb/perform/JvctbPerformer.java#L257-L284
if I then go and save any configuration afterwards the password is now in clear text on the Jenkins instance

😭 
https://github.com/jenkinsci/violation-comments-to-stash-plugin/blob/0e85c4f0d557f03f9a5a6b108af9f90bac9de1d5/src/main/java/org/jenkinsci/plugins/jvctb/perform/JvctbPerformer.java#L235

**Comment by tomasbjerre** [comment]
Nice! It all sounds very good!

I am generally a bit frustrated about the terrible API:s in Jenkins. And credentials is not an exception. Undocumented, lots of deprications and just very unclear how it should be used. Often feels like things are unnecessary complex... So if your refactorings are more then welcome =)

Your findings probably needs fixing in these plugins as well:
* https://github.com/jenkinsci/violation-comments-to-gitlab-plugin
* https://github.com/jenkinsci/violation-comments-to-github-plugin

**Comment by casz** [comment]
@tomasbjerre after a little tweaking. I got this.
![image](https://user-images.githubusercontent.com/1661688/35355642-3bc8a64e-014e-11e8-86a8-1a0df246fbbc.png)

Current progress on simplified generator:
ViolationsToBitbucketServer([violationConfigs: [[parser: 'ANDROIDLINT', pattern: 'b', reporter: 'a'], [parser: 'CHECKSTYLE', pattern: 'b', reporter: 'a']]])

In the process of deprecating username, password 👍

**Comment by casz** [comment]
whats the default behaviour between `create one comment per violation` and `create one big comment with all violations`

**Comment by tomasbjerre** [comment]
I think the first one is most used. I would vote for that being default.

**Comment by tomasbjerre** [comment]
This is now released in 1.65. Thanks again for this!!
