### ISSUE TITLE
Parameter Documentation

### ISSUE THREAD

**Issue by WorkHorseIndustries** [jenkinsci/violation-comments-to-stash-plugin#53]
I can figure out what most of the parameters are used for by their name but I'm confused about  `commentOnlyChangedContentContext`,  would you explain what this number means? I was also wondering if the comments can be restricted to only added changes.  I'm seeing linting errors referring to deleted content, which I found distracting and unhelpful.

**Comment by tomasbjerre** [comment]
With a context of `5`, any violation reported between line 5 and 15 will be included.

Did you perform the merge before doing the analysis? It will not work unless you first merge (without pushing!). The lines will not match the lines in the pull request unless the analysis is done on the merged branches.
