### ISSUE TITLE
All violations related to one file in one comment

### ISSUE THREAD

**Issue by lelik9** [jenkinsci/violation-comments-to-stash-plugin#59]
Is it possible to put all violation which related to a same file in one comment?

**Comment by tomasbjerre** [comment]
You can configure a custom template, if that helps you. If what you want is to reduce the size of the comments.

**Comment by lelik9** [comment]
Yes, I want to reduce amount of comments. How should I configure custom template?
But I suppose it will be the same as ```Create one big comment with all violations``` option. Am I correct?
Also I looked into bitbucket documentation, and it seems to be impossible to create one comment with a few anchors.

**Comment by tomasbjerre** [comment]
The custom template only applies to each comment. If you create one big comment, this template will be used to render each violation within that big comment.

So you cannot reduce the amount of comments, but you can reduce the text in them.

In a pipeline you can configure a custom template with:
```
  ViolationsToBitbucketServer([
   bitbucketServerUrl: 'http://localhost:7990/',
   commentOnlyChangedContent: true,
   commentOnlyChangedContentContext: 5,
   createCommentWithAllSingleFileComments: false,
   createSingleFileComments: true,
   keepOldComments: true,
   projectKey: 'PROJ', // Use environment variable here
   pullRequestId: '1', // Use environment variable here
   repoSlug: 'violations-test', // Use environment variable here
   
   credentialsId: 'theid',
   
   commentTemplate: """
   **Reporter**: {{violation.reporter}}{{#violation.rule}}
   
   **Rule**: {{violation.rule}}{{/violation.rule}}
   **Severity**: {{violation.severity}}
   **File**: {{violation.file}} L{{violation.startLine}}{{#violation.source}}
   
   **Source**: {{violation.source}}{{/violation.source}}
   
   {{violation.message}}
   """,
   
   violationConfigs: [
    // Many more formats available, check https://github.com/tomasbjerre/violations-lib
    [parser: 'FINDBUGS', pattern: '.*/findbugs/.*\\.xml\$', reporter: 'Findbugs'],
    [parser: 'CHECKSTYLE', pattern: '.*/checkstyle/.*\\.xml\$', reporter: 'Checkstyle']
   ]
  ])
```

**Comment by lelik9** [comment]
Okay, yhanks.
And one more question, is it possible to remove this line ```<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF> <a-1204338283>``` from a comment?

**Comment by tomasbjerre** [comment]
No it has to be there.

With Github and Gitlab it is possible to render it invisible with markdown. Perhaps it is possible in Bitbucket also.

**Comment by lelik9** [comment]
Thank you.
