### ISSUE TITLE
Allow INFO Files changed to include all scanned files

### ISSUE THREAD

**Issue by FallibleFlyer** [jenkinsci/violation-comments-to-stash-plugin#62]
Currently the plugin reads the various violation files and parses the output. However, if the file includes four scanned files it will only feed back the two that were changed in the pull request (example below). This is becoming an issue for me as we use ansible-lint which will scan dependencies/imported files. There is no setting to disable it there either and I'm not opposed to the files being scanned, more that the output is being suppressed by this plugin and not being fed back like the rest. 

I realize there would be no file to associate the comments with and it would have to be a Pull Request level comment.

**Comment by tomasbjerre** [comment]
There is now a config `commentOnlyChangedFiles` that can be set to `false` to make it comment with every violation found. Not only the ones on changed files.
