### ISSUE TITLE
Violation plugin iterates over files not mentioned in report

### ISSUE THREAD

**Issue by vzabawski** [jenkinsci/violation-comments-to-stash-plugin#63]
Violation plugin scans all files in pull request and tries to get information about them even if ther are not mentioned in report file:

<img width="706" alt="2019-02-12_16h04_46" src="https://user-images.githubusercontent.com/17778043/52637719-1a94f600-2ee1-11e9-8a7b-a5416ae64af8.png">

Here's my plugin configuration:

<img width="708" alt="2019-02-12_16h00_31" src="https://user-images.githubusercontent.com/17778043/52637722-21bc0400-2ee1-11e9-8ef3-65d3debc8b13.png">
This behavior slows down build process because build is not finished until all files are processed.

Even after I changed commentOnlyChangedContent to *true*, nothing changed and plugin keeps iteration over all files in pull request.

Info
---

 * Plugin version: 1.97
 * Jenkins version: 2.150.2

**Comment by tomasbjerre** [comment]
First requests gets all changes.

The following requests are looking for old comments. Old comments made by findings in previous analysis. With a previous report file where it they might have been mentioned.

https://github.com/tomasbjerre/violation-comments-to-bitbucket-server-lib/blob/master/src/main/java/se/bjurr/violations/comments/bitbucketserver/lib/BitbucketServerCommentsProvider.java#L111

**Comment by vzabawski** [comment]
Is there any way to change such behavior? Right now, those API calls take 90% of build time for some jobs.

<img width="663" alt="2019-02-12_16h39_51" src="https://user-images.githubusercontent.com/17778043/52639369-2a163e00-2ee5-11e9-88d2-fa9f49b4689c.png">

I've tried to adjust plugin parameters, so current parameters look like:

<img width="340" alt="2019-02-12_16h43_34" src="https://user-images.githubusercontent.com/17778043/52639494-76617e00-2ee5-11e9-8721-8b1ec706d777.png">

Those adjustments allowed to decrease build time by ~30% but API calls part still takes a lot of time.
So, is there any way to change this behavior?
Thanks in advance.

**Comment by tomasbjerre** [comment]
If the `createSingleFileComments` is `false`, then I think it should be no problem avoiding these calls.

**Comment by vzabawski** [comment]
It can be achieved by enabling "Create one big comment with all violations" in UI, right?

**Comment by tomasbjerre** [comment]
Yes. This plugin just needs a change in the implementation first.

**Comment by tomasbjerre** [comment]
Just released a fix in version 1.99 now.
