### ISSUE TITLE
Pipeline plugin compatibility

### ISSUE THREAD

**Issue by gips0n** [jenkinsci/violation-comments-to-stash-plugin#7]
I'd be great if we could use this plugin from a `Jenkinsfile`!

The plugin repo has a [compatibility guide](https://github.com/jenkinsci/pipeline-plugin/blob/master/DEVGUIDE.md).

**Comment by tomasbjerre** [comment]
Im working on #5 right now. It will change alot in the plugin so this should probably be done after #5.

**Comment by tomasbjerre** [comment]
This may be fixed now in 1.16. But I have done very little testing =) Closing issue, open it again if its not working!
