### ISSUE TITLE
Report the "indent" level of an issue

### ISSUE THREAD

**Issue by pjaitken** [jenkinsci/violation-comments-to-stash-plugin#78]
Can the "indent" level of an issue be captured and reported?

eg, clang-tidy identifies the same issue twice in one line:
```
src/sfp.c:1186:19: warning: narrowing conversion from "int" to "float" [bugprone-narrowing-conversions]
src/sfp.c:1186:28: warning: narrowing conversion from "int" to "float" [bugprone-narrowing-conversions]
```

However the plugin loses the "19" and "28", and reports `File: src/sfp.c line 1186` twice - which looks like duplication.

Thanks.

**Comment by tomasbjerre** [comment]
Did you try adding {{violation.column}} to the template?

**Comment by pjaitken** [comment]
Perfect, thanks! Where can I find this documented?

**Comment by tomasbjerre** [comment]
Here: https://github.com/tomasbjerre/violation-comments-lib

This repo should probably link to that...

**Comment by pjaitken** [comment]
Sorry, I don't see it there - nor do I see it anywhere in the code:
```
$ git clone https://github.com/tomasbjerre/violation-comments-lib.git
...
$ cd violation-comments-lib
$ grep -ri column
$ 
```

**Comment by tomasbjerre** [comment]
The readme of that repo refers to:
https://github.com/tomasbjerre/violation-comments-lib/blob/master/src/main/java/se/bjurr/violations/comments/lib/model/ViolationData.java
And that class extends:
https://github.com/tomasbjerre/violations-lib/blob/master/src/main/java/se/bjurr/violations/lib/model/Violation.java
In that class you will find column.

**Comment by pjaitken** [comment]
Thanks; it was too many levels of indirection: once I go from the readme to violation-comments-lib ViolationData.java, it's not obvious to find violations-lib ViolationData.java.

However, it's working nicely now. Thanks for your help!
